# Generated by Django 4.2.3 on 2023-09-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_perfil_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='avatar',
            new_name='imagen',
        ),
    ]
